theme: jekyll-theme-minimal

title: Daniel's Data Science Quest!
description: A personal study collection for Data Science.

author:
  name: Daniel Moraite

social-network-links:
  email: "moraite.daniel@gmail.com"
  linkedin: "daniel-moraite-29055115"
  twitter: "danielmoraite"

share-links-active:
  twitter: true
  linkedin: true
